### ISSUE TITLE
sleep problem

### ISSUE THREAD

**Issue by bugraduz** [mohamedspicer/hackintosh-T480s#1]
pc never wake up on sleep mode.

**Comment by m4salah** [comment]
can you give us more information, is your laptop T480s ?

**Comment by bugraduz** [comment]
ı have t480 i5-8550u UHD620

**Comment by m4salah** [comment]
do you have dGPU activated or diable it from BIOS, my sleep mode working perfectly do u use my EFI file ?

**Comment by m4salah** [comment]
Not enough information
