### ISSUE TITLE
Failed to load configuration

### ISSUE THREAD

**Issue by vistree** [mohamedspicer/hackintosh-T480s#11]
OpenCore is not working as boot option. I get "Faild to load configuration"
I need to go to Boot Menu (F12), boot from SSD - then I get OC boot option and can start Mac OS X

**Comment by m4salah** [comment]
this happen to me i don't know why, check out to the commit before the last and it will work, i will search for it in the future

**Comment by a85139138** [comment]
I also encountered this issue, now I use the BOOTx64.efi of 0.6.2 with the newest(0.6.4) OpenCore.efi and Bootstrap.efi, everything worked except WLAN(ax210 not working currently)

**Comment by motorium** [comment]
Hi! Any updates on this issue? A workaround with 0.6.2 doesn't work for me.

**Comment by m4salah** [comment]
check the commit before last

**Comment by m4salah** [comment]
I updated oc to 0.6.8 check it
