### ISSUE TITLE
Fan control

### ISSUE THREAD

**Issue by javasopp** [mohamedspicer/hackintosh-T480s#15]
Excuse me, can your efi adjust the speed of the fan? If not, do you have the corresponding ideas to refer to? thanks

**Comment by m4salah** [comment]
the fan speen adjusted automatically, i have no idea how to adjust the fan speed manually.
you can look here https://github.com/tylernguyen/x1c6-hackintosh maybe you can find what you want maybe not I'm not sure

**Comment by javasopp** [comment]
oh,thank you
