### ISSUE TITLE
Trackpad and Trackpoint went wrong at sometimes.

### ISSUE THREAD

**Issue by xiaotianxt** [mohamedspicer/hackintosh-T480s#3]
My trackpad and trackpoint always went wrong at sometimes with your EFI, it happens randomly and can be restored by rebooting.

Thanks for the share of your EFI, it saves a lot of time!

**Comment by m4salah** [comment]
im very very sorry for the late response, what is the update now ?

**Comment by xiaotianxt** [comment]
Haha that's fine. I've gave up your files and found someone else's to ignore the issue😂
