### ISSUE TITLE
Can the camera be used? The readme file is not written, is it not working?

### ISSUE THREAD

**Issue by bdragonh** [mohamedspicer/hackintosh-T480s#4]
Can the camera be used? The readme file is not written, is it not working?

**Comment by m4salah** [comment]
than you for the issue the camera is surely not working sorry I'm not using the camera so much I will see what I can do about it.

**Comment by m4salah** [comment]
okay, I updated the EFI the camera is working now with me you can test the new EFI and tell me the result if that solves your issue feel free to close the issue.

**Comment by bdragonh** [comment]
Camera can be used, newly found problem (win10 system cannot use fingerprint device)

**Comment by m4salah** [comment]
I'm not sure about the fingerprint I have never used it in the windows or Linux or even Hackintosh
