### ISSUE TITLE
The brightness is adjustable, but the minimum brightness is too bright

### ISSUE THREAD

**Issue by bdragonh** [mohamedspicer/hackintosh-T480s#7]
The brightness is adjustable, but the minimum brightness is too bright

**Comment by m4salah** [comment]
it's too low for me, do use the laptop in dark room

**Comment by a85139138** [comment]
I guess your laptop is the model with dGPU(MX150), you need to disable it in boot-arg

> The brightness is adjustable, but the minimum brightness is too bright
